package com.demands.infraestructure.entity;

public enum DemandType {
    OPERATIONAL,
    STRATEGIC,
    PROJECT,
    INCIDENT,
    SIMPLE,
    COMPLEX,
    HIGH_PRIORITY,
    MEDIUM_PRIORITY,
    LOW_PRIORITY,
    TO_DO,
    IN_PROGRESS,
    COMPLETED,
    CANCELED,
    PENDING,
    DEVELOPMENT,
    MARKETING,
    SUPPORT,
    ADMINISTRATIVE,
    SALES,
    PRODUCTION,
    HUMAN_RESOURCE,
    Email,
    Research,
    Partnerships,
    Coding,
    Documentation,
    Investigation,
    Meeting
}
